__author__ = 'Folaefolc'
"""
Code par Folaefolc
Licence MIT
"""

W, H = 800, 600
TITLE = ""
VERSION = "0.0.1"
TILE_SIZE = 30
FPS = 60
DEBUG_LEVEL = 2
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
MAP_DEFAULT_LENGTH = 1024
MAP_DEFAULT_FLATNESS = 1
MAP_DEFAULT_HEIGHT = W // TILE_SIZE + 1
MAP_DEFAULT_HEAD_START = (H // TILE_SIZE) // 2
MAP_DEFAULT_DENIV = 1